### ISSUE TITLE
peer0.org1 invoke, peer0.org1 can query, but the query result is different from what peer0.org2 query

### ISSUE THREAD

**Issue by will-hu-0** [tubackkhoa/hyperledger-swarm#1]
I am using the solo mode, running with 2 swarm managers.
Deploying with multiple stacks under same overlay network.
I may install/instantiate chaincode successfully for different peers.
However, when I do a invoke from peer0.org0, i may query the correct result from peer0.org0. BUT when I switch the cli with context with peer0.org1, i did a query again, guess what? different.
Looks the synchronization has not been working for some reason?

**Comment by tubackkhoa** [comment]
I suggest you using kubernetes because it is easier to setup and config
https://github.com/agiletechvn/fabric-k8s

**Comment by will-hu-0** [comment]
Thanks.. I will have a close look at that part.
